--CREATE DATABASE
CREATE DATABASE DA;

--USE DATABASE DA IN WHICH TABLE WILL BE STORED
USE DA;

--CREATE TABLE student in DATABASE DA
CREATE TABLE student(
ID INT, 
NAME VARCHAR(50),
DEPT VARCHAR(50)
);

--RETRIVE student TABLE TO VIEW IT
SELECT * FROM student;

--ADDED GENDER COLUMN IN THE EXISTING TABLE student
ALTER TABLE student
ADD GENDER CHAR;

--USED ALTER UERY TO DROP GENDER COLUMN
ALTER TABLE student
DROP COLUMN GENDER;

--INSERTED VALUES IN THE student TABLE 
INSERT INTO student VALUES (1,'NICK', 'IT', 'M'),
(2,'KYLIE', 'HR', 'F'),
(3, 'JERRY', 'HR', 'M'),
(4, 'JOHN', 'DA', 'M'),
(5, 'JENNY', 'IT', 'F');

--USED TO UPDATE ANY VALUE IN TABLE
UPDATE student
SET DEPT = 'DA'
WHERE ID = 5;

